### ISSUE TITLE
Uploading Images with a Story

### ISSUE THREAD

**Issue by DrewBarlow** [Shah-Kush/TellMeAStory4#9]
As a user, I want to be able to upload images with my stories because it helps represent my story.

**Comment by Shah-Kush** [comment]
Reassigned in Iteration 2 to split workload on undersized stories.

**Comment by Shah-Kush** [comment]
Tests are located in story/tellmeastory/tests/test_imageOnNode.py and story image media is in story/media/storyimages. A test image has been provided to run tests and it is called test_image.jpeg.
